sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: Ux2fixBeuL1qGrIq6LpAitTJjUgqY7GVDwJqFa+20HIY/IBFULRWE98/BZq3pYzdRYnALDPdAPvQzWvVWpQ7DRnA7KiYENVBPLuPLNyl/fX7P+NVcih2u0P/nntNrNoAKl2Q5AjI1aUB5w63TotZoQhVqROSlxkmtd0VUxe/XFaPMBIpYhg7XC5HuQjNl4Ay2dvQvM6vUeMDtznH1Pc6uAu99of1KS9ITe6g9xDjkzN/cGzdhWeXTG61vNVfVUrT8KZwDKZrJtqx7gDUToawHqtUzhXZtmE71DDQI0APgQVWfiVs09zLBunRUuRU/XbnINML1ou6Evg3JkhxZ2tvFTxhJFjzDnvXQxJXQX+RgQNHpfM2FiNDT/pFl4Q9CpnuLMH/GUk2Lnmza0e0aUZOZ11eHtOCLD67+LUwxipyRTfIR0ngpy6EU65RJxYU0IMvWPYm4guG/a9wbMT08qG4Q1LUpHMWBdGREKVx9SIrH5OBNkOGQMOawvMExptyIAPCtALLLOB7iRR91hlPn8+qFL4TN3lXjZ9va+ESW2UpjkfyybuCLp5xqIRqYpDywZ8sc497x7QujiySNgwmPHJKTiEIAuEIKVootPoXtiOGP0aOhXww7IOkGn+VrDRGY7jkKe1CYZTlZsuSmb2OmzLCgA4pEQpRma022baPUs66dAo=
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
